services:

  justjelly:
    image: ghcr.io/bezilon/justjelly:latest
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    restart: unless-stopped
    ports:
      - ${JUSTJELLY_PORT}:3000
    depends_on: 
      - postgresql

  database:
    env_file: database.env

    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
 
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
