name: Publish JustJelly Docker Image 

# Only allow this workflow to run once per workflow and event type/number
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:

      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Generate Image Tag
        run: |
          if [ "${GITHUB_REF##*/}" == "main" ]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Pull the latest image (if any) to provide cache layers
      - name: Pull Latest
        run: docker pull bezilon/justjelly:latest || true

      # https://github.com/docker/metadata-action
      - name: Prepare Docker Metadata
        id: docker_metadata # you'll use this in the next step
        uses: docker/metadata-action@v4
        with:
          # List of Docker images to use as base name for tags
          images: bezilon/justjelly
          flavor: latest=true
          # Docker tags based on the following events/attributes
          tags: |
            type=raw,value=${{ env.DOCKER_TAG }}
          #   # set latest tag for master branch
          #   type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
          #   type=schedule
          #   type=ref,event=branch
          #   type=ref,event=pr
          #   type=semver,pattern={{version}}
          #   type=semver,pattern={{major}}.{{minor}}
          #   type=semver,pattern={{major}}
          #   type=sha

      # https://github.com/docker/build-push-action
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.nextjs
          # platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
